(** Factory: set of `term`s *)
type t

(** Term handle given from factory *)
type term

type name = string

(** Underlying implementation of term: instantiate with create_... functions *)
type node = private
  | Bvar of int (* de Bruijn index *)
  | Fvar of name (* free variable, generated by rules *)
  | Mvar of name
    (* meta variable, used in rule definition. Cannot appear in the tableau *)
  | App of name * node ref list
  | Bind of name * node ref

(** Perform pattern matching on the result of this function *)
val term_match : term -> node

(** Empty factory *)
val empty : t

(* Factory to string recursively *)
val string_of_factory : t -> string

(* Factory to string with partial addresses *)
val debug_string_of_factory : t -> string

val cardinal : t -> int

val is_bvar : term -> int option
val is_fvar : term -> string option
val is_mvar : term -> string option
val is_app : term -> (string * term list) option
val is_bind : term -> (string * term) option

val create_bvar : int -> t -> (term * t)
val create_fvar : string -> t -> (term * t)
val create_mvar : string -> t -> (term * t)
val create_app : string -> term list -> t -> (term * t)
val create_bind : string -> term -> t -> (term * t)

(** Term to string recursively *)
val string_of_term : (term -> string)

(** Term comparison: a - b *)
val term_compare : term -> term -> int

(** Term equality comparison: a = b assuming they are from the same factory *)
val term_equal : term -> term -> bool
