type name = string

(* Term with references *)
type term =
  | Bvar of int (* de Bruijn index *)
  | Fvar of name (* free variable, generated by rules *)
  | Mvar of name
    (* meta variable, used in rule definition. Cannot appear in the tableau *)
  | App of name * term ref list
  | Bind of name * term ref

(* Dereference term ref *)
let term_deref t = !t

(* List of term ref to list or term *)
let term_list_deref l = List.map term_deref l

(* Compare terms for Set implementation *)
let rec term_ref_compare a b =

  (* Compare App variants for Set implementation *)
  let term_app_compare a_name a_terms b_name b_terms =
    let name_comparison = compare a_name b_name in
    if name_comparison <> 0 then
      name_comparison
    else
      let arity_comparison = compare (List.length a_terms) (List.length b_terms) in
      if arity_comparison <> 0 then
        arity_comparison
      else
        let combined_terms = List.combine a_terms b_terms in
        let term_tuple_compare tup = match tup with (a, b) -> term_ref_compare a b in
        let term_comparisons = List.map term_tuple_compare combined_terms in
        let non_zero_comparison c = c <> 0 in
        let first_non_zero_comparison = List.find_opt non_zero_comparison term_comparisons in
        Option.value first_non_zero_comparison ~default:0 in

  match !a with
  | Bvar a_bvar -> (
    match !b with
    | Bvar b_bvar -> compare a_bvar b_bvar
    | _ -> 1
  )
  | Fvar a_fvar -> (
    match !b with
    | Bvar _ -> -1
    | Fvar b_fvar -> compare a_fvar b_fvar
    | _ -> 1
  )
  | Mvar a_mvar -> (
    match !b with
    | Bvar _ | Fvar _ -> -1
    | Mvar b_mvar -> compare a_mvar b_mvar
    | _ -> 1
  )
  | App (a_app_name, a_app_terms) -> (
    match !b with
    | Bvar _ | Fvar _ | Mvar _ -> -1
    | App (b_app_name, b_app_terms) ->
      term_app_compare a_app_name a_app_terms b_app_name b_app_terms
    | _ -> 1
  )
  | Bind (a_bind_name, a_bind_term) -> (
    match !b with
    | Bvar _ | Fvar _ | Mvar _ | App _ -> -1
    | Bind (b_bind_name, b_bind_term) ->
      let name_comparison = compare a_bind_name b_bind_name in
      if name_comparison <> 0 then
        name_comparison
      else
        term_ref_compare a_bind_term b_bind_term
  )

(* Module for Set implementation *)
module FactoryTerm = struct 
  type t = term ref
  let compare = term_ref_compare
end

module FactoryTermSet = Set.Make(FactoryTerm)

(* Factory is a set of terms using term_ref_compare to tell them apart *)
type t = FactoryTermSet.t

(* term to string implementation from compile.ml *)
let string_of_term t =
  let rec string_of_term = function
      | Bvar i -> Printf.sprintf "#%d" i
      | Fvar x -> "'" ^ x
      | Mvar x -> "?" ^ x
      | App (f, []) -> f
      | App (f, args) ->
          Printf.sprintf "%s(%s)" f
            (String.concat ", " (List.map string_of_term (term_list_deref args)))
      | Bind (b, body) -> Printf.sprintf "%s.(%s)" b (string_of_term (term_deref body))
    in
    string_of_term t

(* Create or get Bvar in factory *)
let create_bvar index factory =
  let term_matches term_ref = (
    match !term_ref with
    | Bvar existing_index -> existing_index = index
    | _ -> false
  ) in
  let existing_search = FactoryTermSet.find_first_opt term_matches factory in (
  match existing_search with
  | Some existing -> (existing, factory)
  | None ->
    let created = ref (Bvar index) in
    let new_factory = FactoryTermSet.add created factory in
    (created, new_factory)
  )

(* Create or get Fvar in factory *)
let create_fvar name factory =
  let term_matches term_ref = (
    match !term_ref with
    | Fvar existing_name -> existing_name = name
    | _ -> false
  ) in
  let existing_search = FactoryTermSet.find_first_opt term_matches factory in (
  match existing_search with
  | Some existing -> (existing, factory)
  | None ->
    let created = ref (Fvar name) in
    let new_factory = FactoryTermSet.add created factory in
    (created, new_factory)
  )

(* Create or get Mvar in factory *)
let create_mvar name factory =
  let term_matches term_ref = (
    match !term_ref with
    | Mvar existing_name -> existing_name = name
    | _ -> false
  ) in
  let existing_search = FactoryTermSet.find_first_opt term_matches factory in (
  match existing_search with
  | Some existing -> (existing, factory)
  | None ->
    let created = ref (Mvar name) in
    let new_factory = FactoryTermSet.add created factory in
    (created, new_factory)
  )

(* Create or get App in factory *)
let create_app name terms factory =
  let term_matches term_ref = (
    match !term_ref with
    | App (existing_name, existing_terms) ->
      (existing_name, existing_terms) = (name, terms)
    | _ -> false
  ) in
  let existing_search = FactoryTermSet.find_first_opt term_matches factory in (
  match existing_search with
  | Some existing -> (existing, factory)
  | None ->
    let created = ref (App (name, terms)) in
    let new_factory = FactoryTermSet.add created factory in
    (created, new_factory)
  )

(* Create or get Bind in factory *)
let create_bind name term factory =
  let term_matches term_ref = (
    match !term_ref with
    | Bind (existing_name, existing_term) ->
      (existing_name, existing_term) = (name, term)
    | _ -> false
  ) in
  let existing_search = FactoryTermSet.find_first_opt term_matches factory in (
  match existing_search with
  | Some existing -> (existing, factory)
  | None ->
    let created = ref (Bind (name, term)) in
    let new_factory = FactoryTermSet.add created factory in
    (created, new_factory)
  )

(* Factory to string *)
let string_of_factory factory =
  if (FactoryTermSet.cardinal factory) = 0 then
    "{}"
  else
    let term_ref_list = FactoryTermSet.to_list factory in
    let term_list = term_list_deref term_ref_list in
    let term_string_list = List.map string_of_term term_list in
    "{ " ^ (String.concat ", " term_string_list) ^ " }"
