type name = string

(* Term with references *)
type term =
  | Bvar of int (* de Bruijn index *)
  | Fvar of name (* free variable, generated by rules *)
  | Mvar of name
    (* meta variable, used in rule definition. Cannot appear in the tableau *)
  | App of name * term list
  | Bind of name * term

(* Address / unique id for x for printing *)
let address_of x = 2 * (Obj.magic x) / 2

let string_address_of x =
  let s = string_of_int (address_of x) in
  let i = 4 in
  String.sub s (String.length s - i) i

let name_compare a b = compare a b
(* Name comparison: by id, then by length, then by contents *)
  (* if a == b then
    0
  else
    let length_comparison = compare (String.length a) (String.length b) in
    if length_comparison <> 0 then
      length_comparison
    else
      compare a b *)

(*
We use a set of custom compare functions instead
of the builtin polymorphic compare function as its
behaviour is not well understood. We know that it
does not always perform comparison by memory address
as 2 different instances of Mvar ("p") compared equal
by the polymorphic compare function. It also makes
unit tests possible at all because we know what to
expect. 
*)

let term_bvar_compare a_index b_index = compare a_index b_index

let term_fvar_compare a_name b_name = name_compare a_name b_name

let term_mvar_compare a_name b_name = name_compare a_name b_name

(* Compare App variants for Set implementation *)
let rec term_app_compare a_name a_terms b_name b_terms =
  let name_comparison = name_compare a_name b_name in
  if name_comparison <> 0 then
    name_comparison
  else
    let arity_comparison = compare (List.length a_terms) (List.length b_terms) in
    if arity_comparison <> 0 then
      arity_comparison
    else
      let () = assert ((List.length a_terms) = (List.length b_terms)) in
      let combined_terms = List.combine a_terms b_terms in
      let term_tuple_compare tup = match tup with (a, b) -> term_compare a b in
      let term_comparisons = List.map term_tuple_compare combined_terms in
      let non_zero_comparison c = c <> 0 in
      let first_non_zero_comparison = List.find_opt non_zero_comparison term_comparisons in
      Option.value first_non_zero_comparison ~default:0

(* Compare Bind variants for Set implementation *)
and term_bind_compare a_name a_term b_name b_term =
  let name_comparison = name_compare a_name b_name in
      if name_comparison <> 0 then
        name_comparison
      else
        term_compare a_term b_term

(* Compare terms for Set implementation (based on memory id) *)
and term_compare (a: term)(b: term) =
  if a == b then
    0
  else
    term_struct_compare a b

(* Compare terms by variant index then by contents recursively *)
and term_struct_compare a b =
  match (a, b) with
  | (Bvar a_bvar, Bvar b_bvar) -> term_bvar_compare a_bvar b_bvar
  | (Bvar _, _) -> -1
  | (_, Bvar _) -> 1
  | (Fvar a_fvar, Fvar b_fvar) -> term_fvar_compare a_fvar b_fvar
  | (Fvar _, _) -> -1
  | (_, Fvar _) -> 1
  | (Mvar a_mvar, Mvar b_mvar) -> term_mvar_compare a_mvar b_mvar
  | (Mvar _, _) -> -1
  | (_, Mvar _) -> 1
  | (App (a_app_name, a_app_terms), App (b_app_name, b_app_terms)) ->
      term_app_compare a_app_name a_app_terms b_app_name b_app_terms
  | (App _, _) -> -1
  | (_, App _) -> 1
  | (Bind (a_bind_name, a_bind_term), Bind (b_bind_name, b_bind_term)) ->
      term_bind_compare a_bind_name a_bind_term b_bind_name b_bind_term

(* let term_compare (a: term) (b: term) =
  let std_comparison = compare a b in
  let id_a = address_of a in
  let id_b = address_of b in
  let address_comparison = compare id_a id_b in
  if std_comparison <> address_comparison then
    let () = Printf.printf
      "[term_compare] a: %s, b: %s, id_a: %d, id_b: %d, std_comparison: %d, address_comparison: %d\n"
      (string_of_term a) (string_of_term b)
      id_a id_b std_comparison address_comparison in
    let () = assert (std_comparison = address_comparison) in
    std_comparison
  else
    std_comparison *)

let term_equal a b = (a == b)

(* Module for Set implementation *)
module FactoryTerm = struct
  type t = term
  let compare = term_compare
end

module FactoryTermSet = Set.Make(FactoryTerm)

(* Factory is a set of terms using term_compare to tell them apart *)
type t = {
  set : FactoryTermSet.t;
}

(* Empty factory *)
let empty = {
  set = FactoryTermSet.empty
}

(* term to string implementation from compile.ml *)
let string_of_term term =
  let rec string_of_term = function
      | Bvar i -> Printf.sprintf "#%d" i
      | Fvar x -> "'" ^ x
      | Mvar x -> "?" ^ x
      | App (f, []) -> f
      | App (f, args) ->
          Printf.sprintf "%s(%s)" f
            (String.concat ", " (List.map string_of_term args))
      | Bind (b, body) -> Printf.sprintf "%s.(%s)" b (string_of_term body)
    in
    string_of_term term

(* Create or get Bvar in factory *)
let create_bvar index factory =
  let target = Bvar index in
  let existing_search = FactoryTermSet.find_opt target factory.set in (
  match existing_search with
  | Some existing ->
    (* Printf.printf "create_bvar(%d).existing: targ %s, exst %s\n" index (string_address_of target) (string_address_of existing); *)
    (existing, factory)
  | None ->
    (* Printf.printf "create_bvar(%d).created: targ %s\n" index (string_address_of target); *)
    let new_factory = { set = (FactoryTermSet.add target factory.set) } in
    (target, new_factory)
  )

(* Create or get Fvar in factory *)
let create_fvar name factory =
  let target = Fvar name in
  let existing_search = FactoryTermSet.find_opt target factory.set in (
  match existing_search with
  | Some existing ->
    (* Printf.printf "create_fvar(%s).existing: targ %s, exst %s\n" name (string_address_of target) (string_address_of existing); *)
    (existing, factory)
  | None ->
    (* Printf.printf "create_fvar(%s).created: targ %s\n" name (string_address_of target); *)
    let new_factory = { set = (FactoryTermSet.add target factory.set) } in
    (target, new_factory)
  )

(* Create or get Mvar in factory *)
let create_mvar name factory =
  let target = Mvar name in
  let existing_search = FactoryTermSet.find_opt target factory.set in (
  match existing_search with
  | Some existing ->
    (* Printf.printf "create_mvar(%s).existing: targ %s, exst %s\n" name (string_address_of target) (string_address_of existing); *)
    (existing, factory)
  | None ->
    (* Printf.printf "create_mvar(%s).created: targ %s\n" name (string_address_of target); *)
    let new_factory = { set = (FactoryTermSet.add target factory.set) } in
    (target, new_factory)
  )

(* Create or get App in factory *)
let create_app name terms factory =
  let target = App (name, terms) in
  let existing_search = FactoryTermSet.find_opt target factory.set in (
  match existing_search with
  | Some existing ->
    (* Printf.printf "create_app(%s, [%d]).existing: targ %s, exst %s\n" name (List.length terms) (string_address_of target) (string_address_of existing); *)
    (existing, factory)
  | None ->
    let new_factory = { set = (FactoryTermSet.add target factory.set) } in
    (* Printf.printf "create_app(%s, [%d]).created: targ %s\n" name (List.length terms) (string_address_of target); *)
    (target, new_factory)
  )

(* Create or get Bind in factory *)
let create_bind name term factory =
  let target = Bind (name, term) in
  let existing_search = FactoryTermSet.find_opt target factory.set in (
    match existing_search with
    | Some existing ->
      (* Printf.printf "create_bind(%s, _).existing: targ %s, exst %s\n" name (string_address_of target) (string_address_of existing); *)
      (existing, factory)
    | None ->
      let new_factory = { set = (FactoryTermSet.add target factory.set) } in
      (* Printf.printf "create_bind(%s, _).created: targ %s\n" name (string_address_of target); *)
      (target, new_factory)
  )

let cardinal factory = FactoryTermSet.cardinal factory.set

(* Factory to string *)
let string_of_factory factory =
  if (cardinal factory) = 0 then
    "{}"
  else
    let term_list = FactoryTermSet.to_list factory.set in
    let term_string_list = List.map string_of_term term_list in
    "{ " ^ (String.concat ", " term_string_list) ^ " }"

(* String of a term with strings of
recursive elements given by `custom_string_of` *)
let string_of_term_custom term custom_string_of =
  let string_of term = match term with
      | Bvar i -> Printf.sprintf "#%d" i
      | Fvar x -> "'" ^ x
      | Mvar x -> "?" ^ x
      | App (f, []) -> f
      | App (f, args) ->
          Printf.sprintf "%s(%s)" f
            (String.concat ", " (List.map custom_string_of args))
      | Bind (b, body) -> Printf.sprintf "%s.(%s)" b (custom_string_of body)
    in
    string_of term

(* String of factory where each element of depth > 0
is written as its address in factory *)
let debug_string_of_factory factory =
  if (FactoryTermSet.cardinal factory.set) = 0 then
    "{}"
  else
    let rec recursive depth term =
      if depth = 0 then
        let compact_string =
          string_of_term_custom term (recursive (depth + 1))
        in
        compact_string ^ "(@" ^ (string_address_of term) ^ ")"
      else
        let string_of_term =
          if (FactoryTermSet.mem term factory.set) then
            "{@" ^ (string_address_of term) ^ "}"
          else
            "{@?" ^ (string_address_of term) ^ "}"
        in
          string_of_term
      in

    let term_list = FactoryTermSet.to_list factory.set in
    let term_string_list = List.map (recursive 0) term_list in
    "{ " ^ (String.concat ", " term_string_list) ^ " }"

let main () =
  let run = false in
  if not run then () else
  (* let a_or_b = App("or", [ref (Fvar "a"); ref (Fvar "b")]) in
  for i = 0 to (Array.length Sys.argv) - 1 do
    Printf.printf "argv[%d] = %s\n" (i) Sys.argv.(i);
  done;
  Printf.printf "a_or_b: %s" (string_of_term a_or_b);; *)
  (*
  let arg_a = ref (Bind ("exists", p)) in
  let arg_b = ref (Bind ("forall", e)) in
  let comparison = term_compare arg_a arg_b in
  Printf.printf "arg_a: %s\n" (string_of_term !arg_a);
  Printf.printf "arg_b: %s\n" (string_of_term !arg_b);
  Printf.printf "comparison: %s\n" (string_of_int comparison);
  *)

  let factory1 = empty in
  let (p, factory2) = create_mvar "p" factory1 in
  let (e, factory3) = create_mvar "e" factory2 in
  let (_, factory4) = create_mvar "p" factory3 in
  let (arg_b, factory5) = create_bind "forall" e factory4 in
  let (arg_a, factory6) = create_bind "exists" p factory5 in
  Printf.printf "arg_b: %s\n" (string_address_of arg_b);

  let (arg_b2, factory7) = create_bind "forall" e factory6 in
  Printf.printf "arg_b2: %s\n" (string_address_of arg_b2);
  Printf.printf "arg_b: %s\n" (string_address_of arg_b);

  let _ = create_bvar 69420 factory1 in
  let _ = create_fvar "69420" factory1 in

  let (_, factory8) = create_app "f" [arg_a; arg_b2; arg_b] factory7 in

  Printf.printf "factory1 (full): %s\n" (string_of_factory factory1);
  Printf.printf "factory1 (debg): %s\n\n" (debug_string_of_factory factory1);
  Printf.printf "factory2 (full): %s\n" (string_of_factory factory2);
  Printf.printf "factory2 (debg): %s\n\n" (debug_string_of_factory factory2);
  Printf.printf "factory3 (full): %s\n" (string_of_factory factory3);
  Printf.printf "factory3 (debg): %s\n\n" (debug_string_of_factory factory3);
  Printf.printf "factory4 (full): %s\n" (string_of_factory factory4);
  Printf.printf "factory4 (debg): %s\n\n" (debug_string_of_factory factory4);
  Printf.printf "factory5 (full): %s\n" (string_of_factory factory5);
  Printf.printf "factory5 (debg): %s\n\n" (debug_string_of_factory factory5);
  Printf.printf "factory6 (full): %s\n" (string_of_factory factory6);
  Printf.printf "factory6 (debg): %s\n\n" (debug_string_of_factory factory6);
  Printf.printf "factory7 (full): %s\n" (string_of_factory factory7);
  Printf.printf "factory7 (debg): %s\n\n" (debug_string_of_factory factory7);
  Printf.printf "factory8 (full): %s\n" (string_of_factory factory8);
  Printf.printf "factory8 (debg): %s\n\n" (debug_string_of_factory factory8);
  ;;

main ()
