(** Factory: set of `term`s *)
type t

type name = string

(** Term given from factory: instantiate with create_... functions *)
type term = private
  | Bvar of int (* de Bruijn index *)
  | Fvar of name (* free variable, generated by rules *)
  | Mvar of name
    (* meta variable, used in rule definition. Cannot appear in the tableau *)
  | App of name * term list
  | Bind of name * term

(** Empty factory *)
val empty : t

(* Factory to string recursively *)
val string_of_factory : t -> string

(* Factory to string with partial addresses *)
val debug_string_of_factory : t -> string

val cardinal : t -> int

val create_bvar : int -> t -> (term * t)
val create_fvar : string -> t -> (term * t)
val create_mvar : string -> t -> (term * t)
val create_app : string -> term list -> t -> (term * t)
val create_bind : string -> term -> t -> (term * t)

(** Term to string recursively *)
val string_of_term : (term -> string)

(** Name/identifier of term (not recursive) *)
val identifier_of_term : (term -> string)

(** Term comparison: a - b *)
val term_compare : term -> term -> int

(** Term equality comparison: a = b assuming they are from the same factory *)
val term_equal : term -> term -> bool

val string_address_of : ?n:int -> 'a -> string
