type name = string

type t =
  | Bvar of int (* de Bruijn index *)
  | Fvar of name (* free variable, generated by rules *)
  | Mvar of name
    (* meta variable, used in rule definition. Cannot appear in the tableau *)
  | App of name * t list
  | Bind of name * t

val var_open : t -> t -> t

type substitution = (name * t) list
type meta_substitution = MetaSubstitution of substitution

val substitute : meta_substitution -> t -> t
val match_terms : t list -> t list -> meta_substitution option

type free_substitution = FreeSubstitution of substitution

val free_substitute : free_substitution -> t -> t
val unify : t -> t -> free_substitution option
