type name = string

type t =
| Bvar of int (* de Bruijn index *)
| Fvar of name (* free variable, generated by rules *)
| Mvar of name
  (* meta variable, used in rule definition. Cannot appear in the tableau *)
| App of name * t list
| Bind of name * t

(* Variants without their contents *)
type variant =
| VBvar
| VFvar
| VMvar
| VApp
| VBind

type t_alias = t

let term_compare (a: t) (b: t) = compare a b

let term_equal a b = (a == b)

(* Module for Set implementation *)
module FactoryTerm = struct
  type t = t_alias
  let compare = term_compare
end

module FactoryTermSet = Set.Make(FactoryTerm)

type factory = {
  set : FactoryTermSet.t;
}

(* Empty factory *)
let empty_factory = {
  set = FactoryTermSet.empty
}

(* term to string implementation from compile.ml *)
let string_of term =
  let rec string_of_term = function
      | Bvar i -> Printf.sprintf "#%d" i
      | Fvar x -> "'" ^ x
      | Mvar x -> "?" ^ x
      | App (f, []) -> f
      | App (f, args) ->
          Printf.sprintf "%s(%s)" f
            (String.concat ", " (List.map string_of_term args))
      | Bind (b, body) -> Printf.sprintf "%s.(%s)" b (string_of_term body)
    in
    string_of_term term

let string_of_full ?(n=4) term =
  if (0 < n) then
    (string_of term) ^ "{@" ^ (Utils.string_address_of ~n:n term) ^ "}"
  else
    string_of term

let identifier_of term =
  match term with
  | Bvar i -> Printf.sprintf "%d" i
  | Fvar x -> x
  | Mvar x -> x
  | App (f, _args) -> f
  | Bind (b, _body) -> b

let get_subterms term =
  match term with
  | Bvar _i -> []
  | Fvar _name -> []
  | Mvar _name -> []
  | App (_name, args) -> args
  | Bind (_name, arg) -> [arg]

let create_or_get_term term factory =
  let existing_search = FactoryTermSet.find_opt term factory.set in (
  match existing_search with
  | Some existing ->
    (existing, factory)
  | None ->
    let new_factory = { set = (FactoryTermSet.add term factory.set) } in
    (term, new_factory)
  )

(* Create or get Bvar in factory *)
let create_bvar index factory = create_or_get_term (Bvar index) factory

(* Create or get Fvar in factory *)
let create_fvar name factory = create_or_get_term (Fvar name) factory

(* Create or get Mvar in factory *)
let create_mvar name factory = create_or_get_term (Mvar name) factory

(* Create or get App in factory *)
let create_app name terms factory = create_or_get_term (App (name, terms)) factory

(* Create or get App in factory *)
let create_const name factory = create_app name [] factory

(* Create or get Bind in factory *)
let create_bind name term factory = create_or_get_term (Bind (name, term)) factory

let factory_cardinal factory = FactoryTermSet.cardinal factory.set

(* Factory to string *)
let string_of_factory factory =
  if (factory_cardinal factory) = 0 then
    "{}"
  else
    let term_list = FactoryTermSet.to_list factory.set in
    let term_string_list = List.map string_of term_list in
    "{ " ^ (String.concat ", " term_string_list) ^ " }"

(* String of a term with strings of
recursive elements given by `custom_string_of` *)
let string_of_term_custom term custom_string_of =
  let string_of term = match term with
      | Bvar i -> Printf.sprintf "#%d" i
      | Fvar x -> "'" ^ x
      | Mvar x -> "?" ^ x
      | App (f, []) -> f
      | App (f, args) ->
          Printf.sprintf "%s(%s)" f
            (String.concat ", " (List.map custom_string_of args))
      | Bind (b, body) -> Printf.sprintf "%s.(%s)" b (custom_string_of body)
    in
    string_of term

(* String of factory where each element of depth > 0
is written as its address in factory *)
let debug_string_of_factory ?(address_digits = 4) factory =
  if (FactoryTermSet.cardinal factory.set) = 0 then
    "{}"
  else
    let rec recursive depth term =
      if depth = 0 then
        let compact_string =
          string_of_term_custom term (recursive (depth + 1))
        in
        compact_string ^ "(@" ^ (Utils.string_address_of ~n:address_digits term) ^ ")"
      else
        let string_of_term =
          if (FactoryTermSet.mem term factory.set) then
            "{@" ^ (Utils.string_address_of ~n:address_digits term) ^ "}"
          else
            "{@?" ^ (Utils.string_address_of ~n:address_digits term) ^ "}"
        in
          string_of_term
      in

    let term_list = FactoryTermSet.to_list factory.set in
    let term_string_list = List.map (recursive 0) term_list in
    "{ " ^ (String.concat ", " term_string_list) ^ " }"

let var_open t u =
  let rec aux k = function
    | Bvar i -> if i = k then u else Bvar i
    | (Fvar _ as t) | (Mvar _ as t) -> t
    | App (f, args) -> App (f, List.map (aux k) args)
    | Bind (b, body) -> Bind (b, aux (k + 1) body)
  in
  aux 0 t

type substitution = (name * t) list
type meta_substitution = MetaSubstitution of substitution

let substitute (MetaSubstitution sigma) t =
  let rec go t =
    match t with
    | Bvar _ | Fvar _ -> t
    | Mvar m -> (
        match List.assoc_opt m sigma with None -> t | Some bound -> go bound)
    | App (f, args) -> App (f, List.map go args)
    | Bind (b, body) -> Bind (b, go body)
  in
  go t

let match_terms (candidate : t list) (pattern : t list) :
    meta_substitution option =
  let rec go (sigma : substitution) cand pat =
    match (cand, pat) with
    | [], [] -> Some sigma
    | [], _ | _, [] -> None
    | c :: cs, p :: ps -> (
        match (c, p) with
        | Bvar i, Bvar j when i = j -> go sigma cs ps
        | Fvar x, Fvar y when x = y -> go sigma cs ps
        | App (f1, args1), App (f2, args2)
          when f1 = f2 && List.length args1 = List.length args2 ->
            go sigma (args1 @ cs) (args2 @ ps)
        | Bind (b1, t1), Bind (b2, t2) when b1 = b2 ->
            go sigma (t1 :: cs) (t2 :: ps)
        | _, Mvar m -> (
            match List.assoc_opt m sigma with
            | None -> go ((m, c) :: sigma) cs ps
            | Some bound -> if bound = c then go sigma cs ps else None)
        | Mvar _, _ -> None
        | _ -> None)
  in
  go [] candidate pattern |> Option.map (fun sigma -> MetaSubstitution sigma)

type free_substitution = FreeSubstitution of substitution

let free_substitute (FreeSubstitution sigma) t =
  let rec go t =
    match t with
    | Bvar _ | Mvar _ -> t
    | Fvar x -> (
        match List.assoc_opt x sigma with None -> t | Some bound -> go bound)
    | App (f, args) -> App (f, List.map go args)
    | Bind (b, body) -> Bind (b, go body)
  in
  go t

let unify t1 t2 =
  let rec occurs x = function
    | Bvar _ | Mvar _ -> false
    | Fvar y -> x = y
    | App (_, args) -> List.exists (occurs x) args
    | Bind (_, body) -> occurs x body
  in
  let rec go (subst : substitution) = function
    | [] -> Some subst
    | (s, t) :: tl -> (
        let s, t =
          ( free_substitute (FreeSubstitution subst) s,
            free_substitute (FreeSubstitution subst) t )
        in
        if s = t then go subst tl
        else
          match (s, t) with
          | Fvar x, t | t, Fvar x ->
              if occurs x t then None else go ((x, t) :: subst) tl
          | Bvar x, Bvar y when x = y -> go subst tl
          | Mvar x, Mvar y when x = y -> go subst tl
          | App (f1, args1), App (f2, args2)
            when f1 = f2 && List.length args1 = List.length args2 ->
              go subst (List.combine args1 args2 @ tl)
          | Bind (b1, body1), Bind (b2, body2) when b1 = b2 ->
              go subst ((body1, body2) :: tl)
          | _ -> None)
  in
  go [] [ (t1, t2) ] |> Option.map (fun sigma -> FreeSubstitution sigma)
