type name = string

type t = private
  | Bvar of int (* de Bruijn index *)
  | Fvar of name (* free variable, generated by rules *)
  | Mvar of name
    (* meta variable, used in rule definition. Cannot appear in the tableau *)
  | App of name * t list
  | Bind of name * t

(* Variants without their contents *)
type variant =
| VBvar
| VFvar
| VMvar
| VApp
| VBind

type factory

type substitutability = {
  fvar : bool;
  mvar : bool;
}

type t_alias = t

module FactoryTerm : sig
  type t = t_alias
  val compare : t -> t -> int
end

val empty_factory : factory

(** Factory to string recursively *)
val string_of_factory : factory -> string

(** Factory to string with partial addresses *)
val debug_string_of_factory : ?address_digits:int -> factory -> string

val factory_cardinal : factory -> int

val create_bvar  : int -> factory -> (t * factory)
val create_fvar  : name -> factory -> (t * factory)
val create_mvar  : name -> factory -> (t * factory)
val create_app   : name -> t list -> factory -> (t * factory)
val create_const : name -> factory -> (t * factory)
val create_bind  : name -> t -> factory -> (t * factory)

(** Term to string recursively *)
val string_of : t -> string

(** Term to string recursively and address with n last digits *)
val string_of_full : ?n:int -> t -> name

(** Name/identifier of term (not recursive) *)
val identifier_of : t -> string

val get_subterms : t -> t list

(** Term comparison: a - b *)
val term_compare : t -> t -> int

(** Term equality comparison: a = b assuming they are from the same factory *)
val term_equal : t -> t -> bool

val make_substitutability : fvar:bool mvar:bool: Term.substitutability

val var_open : t -> t -> t

type substitution = (name * t) list
type meta_substitution = MetaSubstitution of substitution

val substitute : meta_substitution -> t -> t
val match_terms : t list -> t list -> meta_substitution option

type free_substitution = FreeSubstitution of substitution

val free_substitute : free_substitution -> t -> t
val unify : t -> t -> free_substitution option
